TARpe22ShopVaitmaa/Models/OpenWeather/OpenWeatherViewModel.cs
namespace TARpe22ShopVaitmaa.Models.OpenWeather
{
    public class OpenWeatherViewModel
    {
        public string City { get; set; }
        public int Timezone { get; set; }
        public double Temperature { get; set; }
        public int Pressure { get; set; }
        public int Humidity { get; set; }
        public string Main { get; set; }
        public string Description { get; set; }
        public double Speed { get; set; }
        public double Lat { get; set; }
        public double Lon { get; set; }
    }
}

TARpe22ShopVaitmaa/Controllers/OpenWeatherController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using TARpe22ShopVaitmaa.Core.Dto.WeatherDtos;
using TARpe22ShopVaitmaa.Core.ServiceInterface;
using TARpe22ShopVaitmaa.Models.OpenWeather;

namespace TARpe22ShopVaitmaa.Controllers
{
    public class OpenWeatherController : Controller
    {
        private readonly IWeatherForecastsServices _openWeatherServices;
        public OpenWeatherController(IWeatherForecastsServices weatherForecastServices)
        {
            _openWeatherServices = weatherForecastServices;
        }

        public IActionResult Index()
        {
            OpenWeatherViewModel vm = new OpenWeatherViewModel();
            return View(vm);
        }

        [HttpPost]
        public IActionResult ShowWeather()
        {
            string city = Request.Form["City"];

            if (!string.IsNullOrEmpty(city))
            {
                OpenWeatherResultDto dto = new();
                dto.City = city;
                _openWeatherServices.OpenWeatherDetail(dto);

                OpenWeatherViewModel vm = new()
                {
                    City = dto.City,
                    Timezone = dto.Timezone,
                    Temperature = dto.Temperature,
                    Pressure = dto.Pressure,
                    Humidity = dto.Humidity,
                    Lon = dto.Lon,
                    Lat = dto.Lat,
                    Main = dto.Main,
                    Description = dto.Description,
                    Speed = dto.Speed
                };

                return View("City", vm);
            }

            return View();
        }
    }
}

TARpe22ShopVaitmaa/Views/OpenWeather/City.cshtml
@model TARpe22ShopVaitmaa.Models.OpenWeather.OpenWeatherViewModel
<h1>City</h1>
<div class="container">
    <div class="form-group col-md-3">
        <h2>Forecast for the selected city</h2>
        <hr />
        <dl class="row">
            <div class="form-group-row">
                <label asp-for="City" class="col-sm-7 col-form-label"></label>
                @Html.DisplayFor(model => model.City)
            </div>
            <div class="form-group-row">
                <label asp-for="Timezone" class="col-sm-7 col-form-label"></label>
                @Html.DisplayFor(model => model.Timezone)
            </div>
            <div class="form-group-row">
                <label asp-for="Lon" class="col-sm-7 col-form-label"></label>
                @Html.DisplayFor(model => model.Lon)
            </div>
            <div class="form-group-row">
                <label asp-for="Lat" class="col-sm-7 col-form-label"></label>
                @Html.DisplayFor(model => model.Lat)
            </div>
            <div class="form-group-row">
                <label asp-for="Temperature" class="col-sm-7 col-form-label"></label>
                @Html.DisplayFor(model => model.Temperature)
            </div>
            <div class="form-group-row">
                <label asp-for="Pressure" class="col-sm-7 col-form-label"></label>
                @Html.DisplayFor(model => model.Pressure)
            </div>
            <div class="form-group-row">
                <label asp-for="Humidity" class="col-sm-7 col-form-label"></label>
                @Html.DisplayFor(model => model.Humidity)
            </div>
            <div class="form-group-row">
                <label asp-for="Main" class="col-sm-7 col-form-label"></label>
                @Html.DisplayFor(model => model.Main)
            </div>
            <div class="form-group-row">
                <label asp-for="Description" class="col-sm-7 col-form-label"></label>
                @Html.DisplayFor(model => model.Description)
            </div>
            <div class="form-group-row">
                <label asp-for="Speed" class="col-sm-7 col-form-label"></label>
                @Html.DisplayFor(model => model.Speed)
            </div>
        </dl>
    </div>
</div>

TARpe22ShopVaitmaa/Views/OpenWeather/Index.cshtml
<form method="post" asp-action="ShowWeather" asp-controller="OpenWeather">
    <div class="form-group col-md-offset-7 col-md-7">
        <h2>Look up the weather info of a city!</h2>
    </div>
    <br />
    <div class="container">
        <input type="text" name="City" value="" />
        <input type="submit" class="btn btn-primary" value="Look up" />
    </div>
</form>